### PR TITLE
Few proposed changes

### PR DESCRIPTION
**Pull request by phdussud**
Hello! I am very impressed with this work. Hardware, FPGA, Firmware, Software... Everything hangs together beautifully. 
I had some trouble on Windows when I tried to record directly from the Wireshark UI. I always get bad packet when I spy on a USB HS like a USB mass storage device. Not a problem if I use the usb_sniffer from the CLI. I solved the problem by creating a file writer thread and a large ring buffer written by the main thread and read by the file writer thread. This is the main contribution of this PR. 
Also
- Fixed some minor typos in output messages
- Enabled the auto detection of USB speed, since the FPGA code supports it. 
Please let me know what you think. 
Thanks, 
Patrick

### CODE REVIEW

**Comment by ataradov** [comment]
I will not merge this as is. I don't like this implementation. If any buffering like this to happen, I'd rather it happen in the USB side.

But I don't think any buffering like this should be necessary to not break the protocol. This was the goal of this design. The flow control is handled by the USB, I submit multiple read requests and process them as they are fulfilled. If at some point all requests are taken, then USB would stall and internal buffer would start overflowing, which would result in dropped packets and overflow flags. But nothing should break.

I will debug and profile this over the weekend. My only Windows PC is like 10 years old, and it struggles to do even file capture. But in this case it is good, as I do see those broken frames. This should not happen, and after a quick look at the code, I think I know why it happens. But I need to have a closer look.

Once that is resolved, slow Wireshark pipe would just result in lost packets, but the protocol would not break. After that we can have a look at adding a configurable maximum buffer size. Because eventually things will overflow.

On Linux I can copy really large files to and from the drive without any capture issues.

For the auto-speed - it was intentionally removed in Wireshark adaptation. PcapNG requires you to pick the protocol ahead of time and it is not possible to change it dynamically. Currently dissectors don't do much with this information, but in theory they could, and defaulting for FS for all speeds is not a good idea. This is also not a huge issue in practice, since you are usually aware of what speed to expect.

The ideal solution here is a new USB wrapper that would allow for dynamic speed changes and for arbitrary text messages, but I don't want to mess with WS side.

**Comment by ataradov** [comment]
And for speed - it also matters for the decoding. With the current patch, LS decoding would be broken, since it filters out line state based on the value of g_opt.capture_speed being CaptureSpeed_LS. And with auto-speed it is never the case.

So, to do auto-speed, there needs to be a separate state that tracks the actual speed, not the configured one.

All this logic was in the original code, but it was pretty ugly and low value, so I just removed it, especially given that PcapNG does not support this either.

**Comment by phdussud** [comment]
Hello. 
I created this PR more for discussion and feedback than hoping for a merger as is. 
I look forward to your experiments on Windows. 
I would like to make sure I understand correctly the flow and its constraints. 
My assumption is that the device and its software needs to record every USB transaction (packet) going through the sniffer path. It can't miss any. This goes even for HS. This isn't so easy since the pipe from the device to the PC is not any faster than HS. Bulk transactions are the best choice for the device -> PC communication in this case. 
I have never observed a protocol disconnect between the device and the PC. But I have observed what I believe are dropped packets, because they always manifest themselves as toggle errors. It makes sense because if we are supposed to get a DATA0 and it is being dropped the next one is going to be DATA1 but the PC side expect a DATA0 toggle. 
The bulk requests are 1MB long which allows for 22ms between response without slowdown. Is this correct? 
If I understand libusb correctly, this means that we need to call lisbusb_handle_event no later than 22ms after the libusb_submit_transfer has been called. Is this correct? 
The only potential source of latency in usb_capture_callback or its callees is the call to fwrite. 
This all work perfectly when Wireshark isn't the one calling usb_sniffer but it does not work with a USB HS mass storage. 
This is the reason I put the ring buffer after the processing of the usb packets. I see that it is equally possible to put it before processing. 
About the speed... I agree with everything you said. Something bothered me and lead me to the auto option but I need to run more experiments to convince myself that I wasn't pursuing a ghost issue. 
Thank you very much for your time! Again I love this project. 
Patrick.

**Comment by ataradov** [comment]
Missing individual packets in the observed data is not ideal, but not a deal breaker. Tools like this are not really designed to intercept massive amounts of traffic. This is more for debugging of logical issues, which you ideally reproduce with a short test. If you are debugging a USB drive, it makes sense to copy a small file rather than a huge one, assuming the issue that is being debugged is there even with small files.

And there is a trigger input to limit the capture only to the point of interest. This trigger may be used by the USB stack to only capture interesting moments. In practice, you really don't want to look though 1000s of packets.

Each request is 1MB and 4 requests are submitted at the time. Those requests are already processed in their own thread inside the libusb, so they happen in parallel with the main flow. Ideally this would be the place for a big capture buffer,  but libusb does not want to have too many requests pending at the same time.

usb_capture_callback() does need to run in 20 ms on average to sustain the flow. 

I think the issue that causes breaks in the flow right now is that in the usb_capture_callback() I call libusb_submit_transfer() before the data is processed. And this submitted transfer overwrites the data  still used in the capture_callback(), so the state machine gets broken.

This also means that in addition to the current buffer, 3 other buffers have been filled. So, something must be very slow..

I will try to fix this part later today and then I would profile the slowness.

I profiled disk writes with just fwrite() with small chunks 100-1500 bytes and on that old PC I get 220 MB/s, which should be fast enough to dump 50 MB/s. So, I'm not sure where the delays are, some profiling would be needed.

The easiest test would be to dump the test stream to disk, given that in my case test stream is received without any issues.

**Comment by ataradov** [comment]
The idea of this design is that if you don't process the stream in 20 ms, then there would be no new transfers submitted and FIFO inside the FPGA would stall, so the sniffed packets would be dropped and corresponding flag would be set.

But the "wrong toggle bit received,... " and "zero bit in the header is not zero ..." errors should never happen. If they happen, it means that the data stream got corrupted, and this should never happen.

**Comment by phdussud** [comment]
I don't think the disk is the problem. As I said, the usb_sniffer by itself has no problem dumping to disk. I can't repro the issue without Wireshark invoking usb_sniffer.

**Comment by ataradov** [comment]
This is something I would have to profile separately. On my PC even dumping to the drive causes issues. So, I would have to deal this this first.

**Comment by phdussud** [comment]
I see what you mean.

**Comment by phdussud** [comment]
I see the overflow detection in the hardware and software code. What I don't see is a special treatment of capture_toggle after an overflow. I don't see how the code won't detect a toggle problem after an overflow due to the USB toggling but not the software.

**Comment by ataradov** [comment]
There is no need for anything special. If the stream is not interrupted, the toggle will always be correct. This is by design. There is no way to handle the case when the toggle is wrong. It is there because I had a couple spare bits left, so I used one for the toggle to potentially detect issues sooner. It is not that useful, really.

This toggle is not related to USB DATA0/DATA1 toggle in any way on either target or host interface.

If PC is not ready to receive the data because it is still processing the old data, then it would not submit a request to libusb and FPGA  will not sent the data once internal buffer is full. The corresponding toggle only toggles on the FPGA side when it successfully committed a full frame into the buffer. If the buffer is full, the frames are just dropped, but toggle stays the same.

This way any slowness anywhere in the chain is only addressed at the very beginning in the capture module in the FPGA. 

This way you always have 4 MB buffer (+ a few KB in the FPGA) that is guaranteed to be free of any drops. After that, the packed drops depend on how fast you can handle those 4 MB.

**Comment by phdussud** [comment]
I get it! Thanks for the explanation!

**Comment by ataradov** [comment]
The complete breakage is now fixed. I also added logging of the maximum processing time. When running from the command line it will just print them on stdout, when running from WS, define environment variable USB_SNIFFER_LOG with the value of log path.

From the command line the worst time I've got was 29 ms when opening large media files from the flash drive.

I do see excessive processing time when running under WS. I've seen times like 1.5 seconds to process a 1 MB buffer.  I'll investigate that next.

**Comment by phdussud** [comment]
Great! Thanks,
Patrick

Patrick
________________________________

**Comment by ataradov** [comment]
I did a bit of profiling and the bottleneck here is either Windows pipe performance or Wireshrak performance when reading from the pipe. It is painfully slow and there is not much you can do with it. You can see how WS UI catches up to a long burst of frames.

The file access is much faster, so if a sustained performance is necessary, then using files is a good solution. 

But as it turns out, on Windows you can submit a lot more transfers to the libusb, so I made the define OS dependent and it is 128 on Windows and I bumped it to 16 on Linux, although it is not really needed. Linux is way faster at all this.

I also tried to set I/O buffer size for the pipe file descriptor and that also seems to work, but a more complicated flushing system would be necessary.

As it is right now, it should sustain bursts up to 128 MB on Windows. I still see a few hardware overflows in large captures, but this does not really affect overall use, since nobody is going to sift though 100K+ packets anyway.

**Comment by phdussud** [comment]
here is a log from the command line, with the latest changes
$ ./usb_sniffer.exe -s hs -l -c --fifo blah.bin
Opening file 'blah.bin'
Opening capture device
Starting capture
Processing time = 1 ms (size = 0 bytes)
Processing time = 6 ms (size = 10240 bytes)
Processing time = 7 ms (size = 888320 bytes)
Processing time = 8 ms (size = 1024000 bytes)
Processing time = 12 ms (size = 1024000 bytes)
Processing time = 14 ms (size = 1024000 bytes)
Processing time = 21 ms (size = 988160 bytes)
Processing time = 22 ms (size = 1024000 bytes)
Processing time = 24 ms (size = 1024000 bytes)

**Comment by ataradov** [comment]
Yes, this is consistent with what I get. And this is mostly file access time. if you remove fwrite() call, the time would be under 5 ms.

**Comment by phdussud** [comment]
Right, I measured the processing time excluding the fwrite before and it was less than 2ms on my machine

**Comment by phdussud** [comment]
here is one from WS
Log started on 15/07/2023 09:23:42.356
09:23:42.356  Arguments:
09:23:42.356  0: 'C:\Users\Patrick\AppData\Roaming\Wireshark\extcap\usb_sniffer.exe'
09:23:42.356  1: '--capture'
09:23:42.356  2: '--extcap-interface'
09:23:42.356  3: 'usb_sniffer'
09:23:42.356  4: '--fifo'
09:23:42.356  5: '\\.\pipe\wireshark_extcap_usb_sniffer_20230715092342'
09:23:42.356  6: '--speed'
09:23:42.356  7: 'hs'
09:23:42.356  8: '--fold'
09:23:42.356  9: '--trigger'
09:23:42.356  10: 'disabled'
09:23:42.356  11: '--limit'
09:23:42.356  12: '0'
09:23:42.362  Opening file '\\.\pipe\wireshark_extcap_usb_sniffer_20230715092342'
09:23:42.362  Opening capture device
09:23:42.414  Starting capture
09:23:45.588  Processing time = 1 ms (size = 100352 bytes)
09:23:47.333  Processing time = 969 ms (size = 1024000 bytes)

**Comment by ataradov** [comment]
So, it looks like performance is a bit better here. In my case I 100% get 1.6-1.8 seconds on 1 M buffers and WS visibly takes this time to display the data. This is not going to improve, but hopefully 128 M buffer is enough for most use cases. Within that buffer any slowdown is due to the OS/libusb,

**Comment by phdussud** [comment]
I think it is due to the Windows pipe implementation. Files have a RAM cache that can be as large as the free RAM. If they haven't modified the pipe implementation in the last 3 years, it has a fixed buffer. Pipes aren't used much on Windows.

**Comment by ataradov** [comment]
There is also probably some overhead with FILE operations vs native winapi calls. It does not feel like performance issue is in the read/write operations, but in the polling. WS is very slow to get the data, and I assume it just does not get notified fast enough.

**Comment by phdussud** [comment]
I understand. Thanks again for this device and your support.

**Comment by dougg3** [comment]
I was seeing the same problem in Windows with Wireshark ending the capture as soon as I plugged in a high-speed flash drive. The new binaries fixed it. Thank you!

**Comment by phdussud** [comment]
About Windows pipes: The buffer size can only be specified at creation time. On windows7+ they can be very large but WS only specify 64KB 
```c
    *handle_out = CreateNamedPipe(
                 utf_8to16(pipename),
                 PIPE_ACCESS_DUPLEX | FILE_FLAG_OVERLAPPED,
                 PIPE_TYPE_BYTE | PIPE_READMODE_BYTE | PIPE_WAIT,
                 1, 65536, 65536,
                 300,
                 &security);
```

**Comment by ataradov** [comment]
I believe it is the same size as on Linux by default. This should be sufficient if receiver reads the data promptly.

**Comment by phdussud** [comment]
I installed a Linux machine with the latest stable version of wireshark. 
Here is the log and the installation details
Log started on 16/07/2023 16:44:12.489
16:44:12.489  Arguments:
16:44:12.489  0: '/home/phdussud/.config/wireshark/extcap/usb_sniffer_linux'
16:44:12.489  1: '--capture'
16:44:12.489  2: '--extcap-interface'
16:44:12.489  3: 'usb_sniffer'
16:44:12.489  4: '--fifo'
16:44:12.489  5: '/tmp/wireshark_extcap_usb_snifferKI0571'
16:44:12.489  6: '--speed'
16:44:12.489  7: 'hs'
16:44:12.489  8: '--fold'
16:44:12.489  9: '--trigger'
16:44:12.489  10: 'disabled'
16:44:12.489  11: '--limit'
16:44:12.489  12: '0'
16:44:12.495  Opening file '/tmp/wireshark_extcap_usb_snifferKI0571'
16:44:12.526  Opening capture device
16:44:12.549  Starting capture
16:44:25.564  Processing time = 1 ms (size = 0 bytes)
16:44:27.812  Processing time = 2 ms (size = 2560 bytes)
16:44:28.080  Processing time = 17 ms (size = 20480 bytes)
16:44:29.732  Processing time = 239 ms (size = 1024000 bytes)




wireshark --version
Wireshark 4.0.6 (Git v4.0.6 packaged as 4.0.6-1~exp1~ubuntu22.04.0~ppa1).

Copyright 1998-2023 Gerald Combs <gerald@wireshark.org> and contributors.
Licensed under the terms of the GNU General Public License (version 2 or later).
This is free software; see the file named COPYING in the distribution. There is
NO WARRANTY; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) using GCC 11.3.0, with GLib 2.72.4, with PCRE2, with zlib
1.2.11, with Qt 5.15.3, with libpcap, with POSIX capabilities (Linux), with
libnl 3, with Lua 5.2.4, with GnuTLS 3.7.3 and PKCS #11 support, with Gcrypt
1.9.4, with Kerberos (MIT), with MaxMind, with nghttp2 1.43.0, with brotli, with
LZ4, with Zstandard, with Snappy, with libxml2 2.9.13, with libsmi 0.4.8, with
QtMultimedia, without automatic updates, with SpeexDSP (using system library),
with Minizip, with binary plugins.

Running on Linux 5.15.0-76-generic, with AMD Ryzen Embedded V1202B with Radeon
Vega Gfx (with SSE4.2), with 6871 MB of physical memory, with GLib 2.72.4, with
PCRE2 10.39 2021-10-29, with zlib 1.2.11, with Qt 5.15.3, with libpcap 1.10.1
(with TPACKET_V3), with c-ares 1.18.1, with GnuTLS 3.7.3, with Gcrypt 1.9.4,
with nghttp2 1.43.0, with brotli 1.0.9, with LZ4 1.9.3, with Zstandard 1.4.8,
with libsmi 0.4.8, with LC_TYPE=en_US.UTF-8, binary plugins supported.

**Comment by ataradov** [comment]
I've got the same exact version with the only difference "Running on Linux 5.15.0-73-generic, with Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (with SSE4.2), with 31812 MB of physical memory", which probably does not matter that much.

I guess there would be some variability. I tried to stress it more after that and the worst I got was ~50 ms. This is still fine, if it happens for a single 1 MB buffer, since there are 16 more that are filled at the same time. Things are consistently slow, then some  packets would be dropped, but at that point you are going to look though 16 MB of data anyway, so you will have to re-think your setup if you are debugging something.

**Pull request closed without merging**
