### PR TITLE
fix: display help info when no args provided

### PR DESCRIPTION
**Pull request by huajijam**
before: 
image
after:
image

### CODE REVIEW

**Comment by ataradov** [comment]
I don't like then programs do this and this is not how command line tools usually behave.

Brief message telling you what to do is enough.

**Comment by huajijam** [comment]
> I don't like then programs do this and this is not how command line tools usually behave.
> 
> Brief message telling you what to do is enough.

but, L144 will not trigger when no args provided

**Comment by huajijam** [comment]
image
image

**Comment by ataradov** [comment]
Yeah, that's a mistake. I'll fix that along with adding better debug info.

**Pull request closed without merging**
